export const images = {
    UserLogo: require('../Assets/images/common/user.png'),
    MessageLogo: require('../Assets/images/common/message.png'),
    LockLogo: require('../Assets/images/common/lock.png'),
    UnlockLogo: require('../Assets/images/common/unlock.png'),
    Book: require('../Assets/images/common/book.png'),
    HighFive: require('../Assets/images/common/highfive.png'),
    SilverCup: require('../Assets/images/common/silver-cup.png'),
    Arrow: require('../Assets/images/common/arrow.png'),
    Home: require('../Assets/images/bottomtab/home.png'),
    History: require('../Assets/images/bottomtab/history.png'),
    Trophy: require('../Assets/images/bottomtab/trophy.png'),
    User: require('../Assets/images/bottomtab/user.png'),
    Rocket: require('../Assets/images/common/rocket.png'),
    Earth: require('../Assets/images/common/earth.png'),
    Sun: require('../Assets/images/common/sun.png'),
    Plane: require('../Assets/images/common/plane.png'),
    Menu: require('../Assets/images/common/foursquare.png'),
    Notification: require('../Assets/images/common/Notification.png'),
    Man: require('../Assets/images/common/man.png'),
    CrossIcon: require('../Assets/images/common/close.png'),
    ThumbIcon: require('../Assets/images/common/thumbs-up.png'),
    RibbonIcon: require('../Assets/images/common/ribbon.png'),
    Heart: require('../Assets/images/common/heartbeat.png'),
    Video: require('../Assets/images/common/video.png'),
    RightIcon: require('../Assets/images/common/check.png'),
    Avatar: require('../Assets/images/common/avatar.png'),
    validity: require('../Assets/images/common/validity.png'),
    ClockIcon: require('../Assets/images/common/alarm.png'),

    Hexagon: require('../Assets/images/common/hexagon.png'),
    Medal: require('../Assets/images/common/medal.png'),
    Globe: require('../Assets/images/common/globe.png'),
    Star: require('../Assets/images/common/star.png'),
    SoftBall: require('../Assets/images/common/softball.png'),
    OnOff: require('../Assets/images/common/OnOff.png'),
    

    Google: require('../Assets/images/common/google.png'),
    Facebook: require('../Assets/images/common/facebook.png'),
    Apple: require('../Assets/images/common/apple.png'),
    Setting :require('../Assets/images/common/settings.png'),
    ZicZac :require('../Assets/images/common/ziczacview.png'),
    EyeView:require('../Assets/images/common/view.png'),
    EyeHide:require('../Assets/images/common/hide.png'),
    link : require('../Assets/images/common/link.png'),
    BlockUser:require('../Assets/images/common/block-user.png'),
    AddFriend:require('../Assets/images/common/addfriend.png'),
}