export default RouteName = {
   Slider: 'Slider',
   SignIn: 'SignIn',
   SignUp: 'SignUp',
   Dashboard: 'Dashboard',
   Home: 'Home',
   Profile: 'Profile',
   History: 'History',
   LeaderBoard: 'LeaderBoard',
   UserDash: 'UserDash',
   Setting: 'Setting',
   Result: 'Result',
   Quiz: 'Quiz',
   QuizQue: 'QuizQue',
   HeaderScreen: 'HeaderScreen',
   Category: 'Category',
   UpdateProfile: 'UpdateProfile',
   ForgotPwd:'ForgotPwd',
   Drawer:'Drawer',
   Refer : 'Refer a Friend',
   Friend : 'Friend List',
   SubCategory : 'SubCategory',
   Demo : 'Demo'
}