export const strings = {
    Label_Question: 'Question ',
    Label_OutOf: ' out of ',
    Label_Scored: 'You Scored ',
    Label_IsNull: /^(?=.*\S).*$/,
    Label_Reg: /\S+@\S+\.\S+/,
    Label_RegEx: /^[\+]?[(]?[0-9]{3}[)]?[-\s\.]?[0-9]{3}[-\s\.]?[0-9]{4,6}$/im,
    Label_CreateOwnGame: 'Create your own game',
    Label_Challenge: 'Challenge Your Friends',
    Label_WatchLeaderBoard: 'Watch LeaderBoard',
    Label_SliderText1: 'Sed ut perspiciats unde omnis natus\nerror sit volupatem accusantium\ndoloremque laudantium',
    Label_SliderText2: "Quizai's mission is to deliver high-quality\n questions in every topic you can imagine.\nMake your quiz and challenge your\nfriends instantly.",
    Label_SliderText3: 'our leaderboard, allow you to measure\nyour progress and see how stack up\nagainst players from all around the\nworld.',
    Label_AlreadyHaveAccount: 'Already have an account?',
    Label_DonTHaveAccount: "Don't have an account",
    LoginLabel_RememberMe: 'Remember me',
    Label_SignIn: 'Signin',
    Label_SignUp: 'Sign Up',
    Label_ForgotPassword: 'Forgot your password?',
    Label_ForgotPassword1: 'Forgot password',
    Label_DonTWorry: "Don't Worry",
    Label_FullName: 'Full Name',
    Label_PassWord: 'Password',
    Label_Result: 'Result',
    Label_Email: 'Email',
    Label_Logout: 'Logout',
    Label_RememberMe: 'Remember me',
    Label_ConfirmPassword: 'Confirm Password',
    Label_GetStarted: 'Get Started',
    Label_Skip: 'Skip',
    Label_Next: 'Next',
    Label_Exit: 'Exit',
    LoginHeader_Catechism: 'Cate',
    LoginHeader_Chism: 'chism',
    LoginLabel_RegisterAccount: 'Register New Account',
    LoginLabel_ForgotPassword: 'Forgot Password?',
    LoginLabel_ForgotPasswordDonTWorry: "Forgot your password? Don't worry  ",
    LoginLabel_DonTHaveAccount: "Don't have an account? ",
    LoginLabel_AlreadyHaveAccount: 'Already have an account? ',
    LoginLabel_Email: 'Email',
    Label_Done: 'Done',
    LoginLabel_Password: 'Password',
    SignUpLabel_CPassword: 'Confirm Password',
    SignUpLabel_FullName: 'Full Name',
    CommonLabel_Email: 'Email',
    CommonLabel_Password: 'Password',
    CommonLabel_CfPassword: 'Confirm Password',
    CommonLabel_NoDataFound: 'No Record Found',
    CommonBtn_SignIN: 'Sign In',
    CommonBtn_SignUP: 'Sign Up',
    SignInLabel_OrSign: 'Or Sign In With',
    Signup_FullName: 'Full Name',
    ForgotPwdHeader_ForgotPassword: 'Forgot Password',
    ForgotLabel_RecoverPassword: 'Recover Password',
    SettingLabel_Language: 'Language',
    SettingLabel_Setting: 'Setting',
    SettingLabel_Profile: 'Profile',
    SettingLabel_Interests: 'Interests',
    SettingLabel_Notification: 'Notifications',
    SettingLabel_DelMyAccount: 'Delete My Account',
    Label_WelComeBack: 'Welcome Back!',

    Label_ChooseCategories: 'Choose Categories',
    Label_SeeAll: 'See All',
    LeaderBoardLabel_LeaderBoard: 'Leaderboard',
    ResultLabel_ChallengesFriend: 'Challenges Friends',
    ResultLabel_Incorrect: 'Incorrect',
    ResultLabel_Correct: 'Correct',
    ResultLabel_Question: 'Question',
    HeaderScreenLabel_LogOut: 'Log Out',
    QuizLabel_JoinQuiz: 'Join in Quiz',
    QuizLabel_Start: 'Start Quiz',
    QuizLabel_MCQ: 'MCQ',
    QuizLabel_QuizType: 'Quiz Type :',
    QuizLabel_NOQ: 'Number Of Question :',
    QuizLabel_QuizDuration: 'Quiz Duration :',
    QuizLabel_Minutes: 'Minutes',
    QuizLabel_AboutThisQuiz: 'About This Quiz',
    QuizLabel_CollegeQuiz: 'College Quiz 2021',
    QuizLabel_QuizFound: 'Quiz Found!',
    ProfileLabel_WorldRank: 'WorldRank',
    ProfileLabel_LocalRank: 'LocalRank',
    ProfileLabel_Score: 'Score',
    ProfileLabel_EditProfile: 'Edit Profile',
    ProfileLabel_Save: 'Save',
    ProfileLabel_Badge: 'Badge',
    Label_InvalidEmail: 'Please enter your valid email ID',
    Label_InvalidPassword: 'Please enter your password',
    Label_InvalidPasswordDontMatch: 'Password you entered is incorrect. please try again',

    Auth_PassError: 'auth/wrong-password',
    Auth_TooManyReq: 'auth/too-many-requests',
    Auth_EmaiError: 'auth/invalid-email',
    Auth_EmailUseError: 'email-already-in-use',
    Auth_UserNotFound: 'auth/user-not-found',
    //validation
    Validate_Empty: 'Please filled the property.',
    Validate_PassEmpty: 'Password must Not have to be empty.',
    Validate_EmailEmpty: 'Email must Not have to be empty.',
    Validate_Password : 'Password must contain one uppercase and lowercase and must contain one special character and length should be 6-8 character  ',
    Validate_Email: 'Please Enter Appropriate Email ID',
    Validate_PassNotContainWhiteSpace: 'Password must not contain Whitespaces.',
    Validate_PassMustUpperCase: 'Password must have at least one Uppercase Character.',
    Validate_PassMustLowerCase: 'Password must have at least one Lowercase Character.',
    Validate_PassMust6to8: 'Password must be 6-8 Characters Long.',
    Validate_PassAtleastOneDigit: 'Password must contain at least one Digit.',
    Validate_PassAtleastOneSpecial: 'Password must contain at least one Special Symbol.',
    Validate_PassNotMatch: "Password doesn't match '\n' User Not Found!!!",
    Validate_EmailNotMatch: "Email doesn't match",
    Validate_EmailUse: 'Email Already in Use!!!. ',
    Validate_UserNotFound: 'User Not Found!!!. ',
    Validate_PassCfrmpassMatch: 'Password & Confirm Password should be Same.',
    CategoryLabel_Line: 'Pick your favourite topics to set up your feed',
    CategoryLabel_Subcategory : 'Sub Category',
    SUCCESS: 'Success',
    ERROR: 'Error',
    WARNING: 'Warning',
    YES_ONLY : 'Yes',
    Logout_Label : 'Are you sure want to logout',
    NO : 'NO'

}

export default strings;