export const strings = {
    Label_Question: 'सवाल ',
    Label_OutOf: ' में से ',
    Label_Scored: 'आपका स्कोर ',
    Label_IsNull: /^(?=.*\S).*$/,
    Label_Reg: /\S+@\S+\.\S+/,
    Label_RegEx: /^[\+]?[(]?[0-9]{3}[)]?[-\s\.]?[0-9]{3}[-\s\.]?[0-9]{4,6}$/im,
    Label_CreateOwnGame: 'Create your own game',
    Label_Challenge: 'Challenge Your Friends',
    Label_WatchLeaderBoard: 'Watch LeaderBoard',
    Label_SliderText1: 'Sed ut perspiciats unde omnis natus\nerror sit volupatem accusantium\ndoloremque laudantium',
    Label_SliderText2: "Quizai's mission is to deliver high-quality\n questions in every topic you can imagine.\nMake your quiz and challenge your\nfriends instantly.",
    Label_SliderText3: 'our leaderboard, allow you to measure\nyour progress and see how stack up\nagainst players from all around the\nworld.',

    Label_AlreadyHaveAccount: 'क्या आपके पास पहले से एक खाता मौजूद है?',
    Label_DonTHaveAccount: "क्या आपके पास खाता नहीं है",
    LoginLabel_RememberMe: 'पहचाना की नहीं ?',
    Label_SignIn: 'लॉग इन करें',
    Label_SignUp: 'साइन अप करें',
    Label_ForgotPassword: 'अपना पासवर्ड भूल गए?',
    Label_ForgotPassword1: 'पासवर्ड भूल गए',
    Label_DonTWorry: "चिंता मत करो",
    Label_FullName: 'पूरा नाम',
    Label_PassWord: 'पासवर्ड',
    Label_Result: 'परिणाम',
    Label_Email: 'ईमेल',
    Label_Logout: 'लॉग आउट',
    Label_RememberMe: 'पहचाना की नहीं',
    Label_ConfirmPassword: 'पासवर्ड की पुष्टि कीजिये',
    Label_GetStarted: 'शुरू हो जाओ  ',
    Label_Skip: 'छोडना',
    Label_Next: 'अगला',
    Label_Exit: 'बाहर निकलना',
    LoginHeader_Catechism: 'Cate',
    LoginHeader_Chism: 'chism',
    LoginLabel_RegisterAccount: 'Register New Account',
    LoginLabel_ForgotPassword: 'Forgot Password?',
    LoginLabel_ForgotPasswordDonTWorry: "Forgot your password? Don't worry  ",
    LoginLabel_DonTHaveAccount: "Don't have an account? ",
    LoginLabel_AlreadyHaveAccount: 'Already have an account? ',
    LoginLabel_Email: 'Email',
    Label_Done: 'Done',
    LoginLabel_Password: 'Password',
    SignUpLabel_CPassword: 'Confirm Password',
    SignUpLabel_FullName: 'Full Name',
    CommonLabel_Email: 'Email',
    CommonLabel_Password: 'Password',
    CommonLabel_CfPassword: 'Confirm Password',
    CommonLabel_NoDataFound: 'No Record Found',
    CommonBtn_SignIN: 'Sign In',
    CommonBtn_SignUP: 'Sign Up',
    SignInLabel_OrSign: 'Or Sign In With',
    Signup_FullName: 'Full Name',
    ForgotPwdHeader_ForgotPassword: 'पासवर्ड भूल गए',
    ForgotLabel_RecoverPassword: 'पासवर्ड की वसूली',
    SettingLabel_Language: 'भाषा',
    SettingLabel_Setting: 'सेटिंग',
    SettingLabel_Profile: 'प्रोफ़ाइल',
    SettingLabel_Interests: 'रूचियाँ',
    SettingLabel_Notification: 'सूचनाएं',
    SettingLabel_DelMyAccount: 'मेरा एकाउंट हटा दो',
    Label_WelComeBack: 'स्वागत है!',

    Label_ChooseCategories: 'श्रेणियाँ चुनें',
    Label_SeeAll: 'सभी देखें',
    // LeaderBoardLabel_LeaderBoard: 'लीडरबोर्ड',
    ResultLabel_ChallengesFriend: 'Challenges Friends',
    ResultLabel_Incorrect: 'ग़लत',
    ResultLabel_Correct: 'सही',
    ResultLabel_Question: 'सवाल',
    HeaderScreenLabel_LogOut: 'लॉग आउट',
    QuizLabel_JoinQuiz: 'प्रश्नोत्तरी में शामिल हों',
    QuizLabel_Start: 'प्रश्नोत्तरी प्रारंभ करें',
    QuizLabel_MCQ: 'प्रश्नोत्तरी',
    QuizLabel_QuizType: 'प्रश्नोत्तरी प्रकार :',
    QuizLabel_NOQ: 'प्रश्न की संख्या :',
    QuizLabel_QuizDuration: 'प्रश्नोत्तरी अवधि :',
    QuizLabel_Minutes: 'मिनट',
    QuizLabel_AboutThisQuiz: 'प्रश्नोत्तरी के बारे में',
    QuizLabel_CollegeQuiz: 'कॉलेज प्रश्नोत्तरी 2023',
    QuizLabel_QuizFound: 'प्रश्नोत्तरी!!',
    ProfileLabel_WorldRank: 'WorldRank',
    ProfileLabel_LocalRank: 'LocalRank',
    ProfileLabel_Score: 'Score',
    ProfileLabel_EditProfile: 'प्रोफ़ाइल संपादित करें',
    ProfileLabel_Save: 'Save',
    ProfileLabel_Badge: 'बिल्ला',
    Label_InvalidEmail: 'Please enter your valid email ID',
    Label_InvalidPassword: 'Please enter your password',
    Label_InvalidPasswordDontMatch: 'Password you entered is incorrect. please try again',

    Auth_PassError: 'auth/wrong-password',
    Auth_TooManyReq: 'auth/too-many-requests',
    Auth_EmaiError: 'auth/invalid-email',
    Auth_EmailUseError: 'email-already-in-use',
    Auth_UserNotFound: 'auth/user-not-found',
    //validation
    Validate_Empty: 'Please filled the property.',
    Validate_PassEmpty: 'Password must Not have to be empty.',
    Validate_EmailEmpty: 'Email must Not have to be empty.',
    Validate_Email: 'Please Enter Appropriate Email ID',
    Validate_PassNotContainWhiteSpace: 'Password must not contain Whitespaces.',
    Validate_PassMustUpperCase: 'Password must have at least one Uppercase Character.',
    Validate_PassMustLowerCase: 'Password must have at least one Lowercase Character.',
    Validate_PassMust6to8: 'Password must be 6-8 Characters Long.',
    Validate_PassAtleastOneDigit: 'Password must contain at least one Digit.',
    Validate_PassAtleastOneSpecial: 'Password must contain at least one Special Symbol.',
    Validate_PassNotMatch: "Password doesn't match",
    Validate_EmailNotMatch: "Email doesn't match",
    Validate_EmailUse: 'Email Already in Use!!!. ',
    Validate_UserNotFound: 'User Not Found!!!. ',
    Validate_PassCfrmpassMatch: 'Password & Confirm Password should be Same.',
    CategoryLabel_Line: 'अपने पसंदीदा विषय चुनें'
}

export default strings;